AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prepasto-whatsapp-sam-app

  Sample SAM Template for prepasto-whatsapp-sam-app

Resources:
  ProcessMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/process_message_lambda/lambda_environment/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 120      # Number of seconds before the lambda times out
      AutoPublishAlias: pullRequestAlias # This is the default alias that will be associated with the function when we do a 'sam deploy'

  StagingProcessMessageAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ProcessMessageFunction # This points to the lambda function the thing we're aliasing
      FunctionVersion: 36 # IMPORTANT: this is a manual toggle to determine which version of the lambda is the 'staging version'.
      Name: stagingAlias

  ProductionProcessMessageAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ProcessMessageFunction # This points to the lambda function the thing we're aliasing
      FunctionVersion: 30 # IMPORTANT: this is a manual toggle to determine which version of the lambda is the live 'production version'.
      Name: production

Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ProcessMessageFunction.Arn
