AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prepasto-whatsapp-sam-app

  Sample SAM Template for prepasto-whatsapp-sam-app

Resources:
  ProcessMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/process_message_lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 60      # Optional: Adjust based on your function's needs

Outputs:
  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ProcessMessageFunction.Arn
