AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  prepasto-whatsapp-sam-app

  Sample SAM Template for prepasto-whatsapp-sam-app

Resources:
  ProcessMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/process_message_lambda/lambda_environment/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 120      # Number of seconds before the lambda times out
      AutoPublishAlias: pullRequestAlias # This is the default alias that will be associated with the function when we do a 'sam deploy'
      Environment:
        Variables: # These are variables stored in our AWS parameter store
          CUSTOM_SEARCH_ID: '{{resolve:ssm:/process_message_lambda/production/custom_search_id:1}}'
          G_SEARCH_API_KEY: '{{resolve:ssm:/process_message_lambda/production/g_search_api_key:1}}'
          LAMBDA_TO_DJANGO_API_KEY: '{{resolve:ssm:/process_message_lambda/production/lambda_to_django_api_key:1}}'
          OPENAI_KEY: '{{resolve:ssm:/process_message_lambda/production/openai_key:1}}'
          PRODUCTION_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/process_message_lambda/production/production_railway_public_domain:1}}'
          PULL_REQUEST_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/process_message_lambda/production/pull_request_railway_public_domain}}' #always just point to the latest PR domain in our variable store
          STAGING_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/process_message_lambda/production/staging_railway_public_domain:1}}'

  StagingProcessMessageAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ProcessMessageFunction # This points to the lambda function the thing we're aliasing
      FunctionVersion: 50 # IMPORTANT: this is a manual toggle to determine which version of the lambda is the 'staging version'.
      Name: stagingAlias

  ProductionProcessMessageAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ProcessMessageFunction # This points to the lambda function the thing we're aliasing
      FunctionVersion: 50 # IMPORTANT: this is a manual toggle to determine which version of the lambda is the live 'production version'.
      Name: production

  ImageToMealDescriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/image_to_meal_description_lambda/lambda_environment/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 120      
      AutoPublishAlias: pullRequestAlias 
      Environment:
        Variables: # These are variables stored in our AWS parameter store
          WHATSAPP_TOKEN: '{{resolve:ssm:/image_to_meal_description_lambda/production/whatsapp_token:1}}'
          DESCRIBE_FOOD_IMAGE_TO_DJANGO_API_KEY: '{{resolve:ssm:/image_to_meal_description_lambda/production/describe_food_image_to_django_api_key:1}}'
          OPENAI_KEY: '{{resolve:ssm:/image_to_meal_description_lambda/production/openai_key:1}}'
          PRODUCTION_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/image_to_meal_description_lambda/production/production_railway_public_domain:1}}'
          PULL_REQUEST_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/image_to_meal_description_lambda/production/pull_request_railway_public_domain}}' #always just point to the latest PR domain in our variable store
          STAGING_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/image_to_meal_description_lambda/production/staging_railway_public_domain:1}}'

  StagingImageToMealDescriptionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ImageToMealDescriptionFunction 
      FunctionVersion: 3
      Name: stagingAlias

  ProductionImageToMealDescriptionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ImageToMealDescriptionFunction 
      FunctionVersion: 3
      Name: production

  GatherNutritionDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/gather_nutrition_data_lambda/lambda_environment/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 120      
      AutoPublishAlias: pullRequestAlias 
      Environment:
        Variables: # These are variables stored in our AWS parameter store
          WHATSAPP_TOKEN: '{{resolve:ssm:/gather_nutrition_data_lambda/production/whatsapp_token:1}}'
          DATABASE_URL: '{{resolve:ssm:/gather_nutrition_data_lambda/production/database_url:1}}'
          WHATSAPP_MEDIA_API_URL: '{{resolve:ssm:/gather_nutrition_data_lambda/production/whatsapp_media_api_url:1}}'
          GATHER_NUTRITION_DATA_TO_DJANGO_API_KEY: '{{resolve:ssm:/gather_nutrition_data_lambda/production/gather_nutrition_data_to_django_api_key:1}}'
          PRODUCTION_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/gather_nutrition_data_lambda/production/production_railway_public_domain:1}}'
          PULL_REQUEST_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/gather_nutrition_data_lambda/production/pull_request_railway_public_domain}}' #always just point to the latest PR domain in our variable store
          STAGING_RAILWAY_PUBLIC_DOMAIN: '{{resolve:ssm:/gather_nutrition_data_lambda/production/staging_railway_public_domain:1}}'

  StagingGatherNutritionDataAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref GatherNutritionDataFunction 
      FunctionVersion: 2
      Name: stagingAlias

  ProductionGatherNutritionDataAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref GatherNutritionDataFunction 
      FunctionVersion: 2
      Name: production

Outputs:
  ProcessMessageFunctionArn:
    Description: "ARN of the ProcessMessageFunction Lambda"
    Value: !GetAtt ProcessMessageFunction.Arn
  
  ImageToMealDescriptionFunctionArn:
    Description: "ARN of the ImageToMealDescriptionFunction Lambda"
    Value: !GetAtt ImageToMealDescriptionFunction.Arn

  GatherNutritionDataFunctionArn:
    Description: "ARN of the GatherNutritionDataFunction Lambda"
    Value: !GetAtt GatherNutritionDataFunction.Arn
