# Generated by Django 5.1 on 2024-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='local_date',
            field=models.DateField(editable=False),
        ),
    ]
