# Generated by Django 5.1 on 2024-08-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='calories',
        ),
    ]
