# Generated by Django 5.1 on 2024-08-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_diary_calories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
    ]
