# Generated by Django 5.1 on 2024-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dish_qualifiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='matched_thalos_id',
            new_name='prepasto_usda_code',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='similar_dishes',
            new_name='similar_foods',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fndds_and_sr_legacy_google_search_results',
        ),
        migrations.AddField(
            model_name='dish',
            name='nutrition_citation_website',
            field=models.CharField(default='USDA', max_length=255),
            preserve_default=False,
        ),
    ]
