# Generated by Django 5.1 on 2024-10-24 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_matched_thalos_id_dish_prepasto_usda_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='calorie_goal',
            field=models.IntegerField(default=2500, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='carb_g_goal',
            field=models.IntegerField(default=313, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='fat_g_goal',
            field=models.IntegerField(default=56, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='protein_g_goal',
            field=models.IntegerField(default=188, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
