# Generated by Django 5.1 on 2024-08-29 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meal_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('custom_user', 'local_date')},
        ),
    ]
