# Generated by Django 5.1 on 2024-10-24 22:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_diary_calorie_goal_diary_carb_g_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='fndds_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='dish',
            name='prepasto_usda_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='usda_food_data_central_food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='usda_food_data_central_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
