# Generated by Django 5.1 on 2024-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_dish_fndds_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='qualifiers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
