# Generated by Django 5.1 on 2024-10-25 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappUser',
            fields=[
                ('whatsapp_wa_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('whatsapp_profile_name', models.CharField(max_length=255)),
                ('time_zone_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_step', models.CharField(choices=[('INITIAL', 'Initial WhatsApp Contact'), ('GOALS_SET', 'Nutrition Goals Set'), ('TIMEZONE_SET', 'Timezone Set'), ('COMPLETED', 'Onboarding Completed')], default='INITIAL', max_length=50)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('calorie_goal', models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g_goal', models.IntegerField(default=188, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_g_goal', models.IntegerField(default=56, validators=[django.core.validators.MinValueValidator(0)])),
                ('carb_g_goal', models.IntegerField(default=313, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_subscribed', models.BooleanField(default=False)),
                ('custom_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('whatsapp_message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('record_created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=20)),
                ('sent_from', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('DELETE_REQUEST', 'DELETE_REQUEST'), ('EDIT_MEAL_REQUEST', 'EDIT_MEAL_REQUEST'), ('DUPLICATE_MEAL_REQUEST', 'DUPLICATE_MEAL_REQUEST'), ('MEAL_EDIT_CONFIRM', 'MEAL_EDIT_CONFIRM'), ('MEAL_EDIT_CANCEL', 'MEAL_EDIT_CANCEL'), ('NUTRITION_DATA_REQUEST', 'NUTRITION_DATA_REQUEST'), ('CONFIRM_NUTRITION_GOALS', 'CONFIRM_NUTRITION_GOALS'), ('CANCEL_NUTRITION_GOALS', 'CANCEL_NUTRITION_GOALS'), ('TIMEZONE_CONFIRMATION', 'TIMEZONE_CONFIRMATION'), ('TIMEZONE_CANCELLATION', 'TIMEZONE_CANCELLATION'), ('SERVICE_UNDERSTANDING', 'SERVICE_UNDERSTANDING'), ('NUTRITION_GOAL_DATA', 'NUTRITION_GOAL_DATA'), ('STATUS_UPDATE_SENT', 'STATUS_UPDATE_SENT'), ('STATUS_UPDATE_READ', 'STATUS_UPDATE_READ'), ('STATUS_UPDATE_FAILED', 'STATUS_UPDATE_FAILED'), ('STATUS_UPDATE_DELIVERED', 'STATUS_UPDATE_DELIVERED'), ('TEXT', 'TEXT'), ('LOCATION_SHARE', 'LOCATION_SHARE'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('DOCUMENT', 'DOCUMENT'), ('PREPASTO_SET_GOALS_FLOW', 'PREPASTO_SET_GOALS_FLOW'), ('PREPASTO_CONFIRM_NUTRITION_BUTTON', 'PREPASTO_CONFIRM_NUTRITION_BUTTON'), ('PREPASTO_LOCATION_REQUEST_BUTTON', 'PREPASTO_LOCATION_REQUEST_BUTTON'), ('PREPASTO_CONFIRM_TIMEZONE_BUTTON', 'PREPASTO_CONFIRM_TIMEZONE_BUTTON'), ('PREPASTO_UNDERSTANDING_BUTTON', 'PREPASTO_UNDERSTANDING_BUTTON'), ('PREPASTO_ONBOARDING_TEXT', 'PREPASTO_ONBOARDING_TEXT'), ('PREPASTO_CONTACT_CARD', 'PREPASTO_CONTACT_CARD'), ('PREPASTO_REQUEST_FEEDBACK', 'PREPASTO_REQUEST_FEEDBACK'), ('PREPASTO_CREATING_MEAL_TEXT', 'PREPASTO_CREATING_MEAL_TEXT'), ('PREPASTO_MEAL_BUTTON', 'PREPASTO_MEAL_BUTTON'), ('PREPASTO_DIARY_TEXT', 'PREPASTO_DIARY_TEXT'), ('PREPASTO_MEAL_DELETED_TEXT', 'PREPASTO_MEAL_DELETED_TEXT'), ('PREPASTO_ERROR_TEXT', 'PREPASTO_ERROR_TEXT'), ('PREPASTO_SUBSCRIPTION_EXPIRED', 'PREPASTO_SUBSCRIPTION_EXPIRED'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_details', models.TextField(blank=True, null=True)),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp_bot.whatsappmessage')),
                ('whatsapp_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.whatsappuser')),
            ],
        ),
    ]
