# Generated by Django 5.1 on 2024-09-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappUser',
            fields=[
                ('whatsapp_wa_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time_zone_name', models.CharField(max_length=50)),
                ('custom_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('whatsapp_message_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('direction', models.CharField(choices=[('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=8)),
                ('message_type', models.CharField(choices=[('USER_ANONYMOUS_TEXT', 'USER_ANONYMOUS_TEXT'), ('PREPASTO_ONBOARDING_TEXT', 'PREPASTO_ONBOARDING_TEXT'), ('PREPASTO_LOCATION_REQUEST_BUTTON', 'PREPASTO_LOCATION_REQUEST_BUTTON'), ('USER_COORDINATES', 'USER_COORDINATES'), ('PREPASTO_CONFIRM_TIMEZONE_BUTTON', 'PREPASTO_CONFIRM_TIMEZONE_BUTTON'), ('USER_CONFIRM_TIMEZONE_PRESS', 'USER_CONFIRM_TIMEZONE_PRESS'), ('USER_CANCEL_TIMEZONE_PRESS', 'USER_CANCEL_TIMEZONE_PRESS'), ('USER_CREATE_MEAL_TEXT', 'USER_CREATE_MEAL_TEXT'), ('PREPASTO_CREATING_MEAL_TEXT', 'PREPASTO_CREATING_MEAL_TEXT'), ('PREPASTO_MEAL_BUTTON', 'PREPASTO_MEAL_BUTTON'), ('PREPASTO_DIARY_TEXT', 'PREPASTO_DIARY_TEXT'), ('USER_MEAL_DELETE_PRESS', 'USER_MEAL_DELETE_PRESS'), ('PREPASTO_MEAL_DELETED_TEXT', 'PREPASTO_MEAL_DELETED_TEXT'), ('PREPASTO_ERROR_TEXT', 'PREPASTO_ERROR_TEXT'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=32)),
                ('content', models.TextField()),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='whatsapp_bot.whatsappmessage')),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.whatsappuser')),
            ],
        ),
    ]
