# Generated by Django 5.1 on 2024-08-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=3),
        ),
    ]
