# Generated by Django 5.1 on 2024-09-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappuser',
            old_name='phone_number',
            new_name='whatsapp_wa_id',
        ),
    ]
