# Generated by Django 5.1 on 2024-09-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
