# Generated by Django 5.1 on 2024-09-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_alter_whatsappmessage_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappmessage',
            old_name='timestamp',
            new_name='record_created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='direction',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='failure_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_from',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_to',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('NEW_USER_TEXT', 'NEW_USER_TEXT'), ('NEW_USER_LOCATION_SHARE', 'NEW_USER_LOCATION_SHARE'), ('NEW_USER_TIMEZONE_CONFIRMATION', 'NEW_USER_TIMEZONE_CONFIRMATION'), ('NEW_USER_TIMEZONE_CANCELLATION', 'NEW_USER_TIMEZONE_CANCELLATION'), ('NEW_USER_MESSAGE_GENERIC', 'NEW_USER_MESSAGE_GENERIC'), ('NEW_USER_STATUS_UPDATE_SENT', 'NEW_USER_STATUS_UPDATE_SENT'), ('NEW_USER_STATUS_UPDATE_READ', 'NEW_USER_STATUS_UPDATE_READ'), ('NEW_USER_STATUS_UPDATE_FAILED', 'NEW_USER_STATUS_UPDATE_FAILED'), ('USER_DELETE_REQUEST', 'USER_DELETE_REQUEST'), ('USER_TEXT', 'USER_TEXT'), ('USER_IMAGE', 'USER_IMAGE'), ('USER_VIDEO', 'USER_VIDEO'), ('USER_MESSAGE_GENERIC', 'USER_MESSAGE_GENERIC'), ('USER_STATUS_UPDATE_SENT', 'USER_STATUS_UPDATE_SENT'), ('USER_STATUS_UPDATE_READ', 'USER_STATUS_UPDATE_READ'), ('USER_STATUS_UPDATE_FAILED', 'USER_STATUS_UPDATE_FAILED'), ('PREPASTO_ONBOARDING_TEXT', 'PREPASTO_ONBOARDING_TEXT'), ('PREPASTO_CONTACT_CARD', 'PREPASTO_CONTACT_CARD'), ('PREPASTO_REQUEST_FEEDBACK', 'PREPASTO_REQUEST_FEEDBACK'), ('PREPASTO_CONFIRM_USER_TEXT', 'PREPASTO_CONFIRM_USER_TEXT'), ('PREPASTO_LOCATION_REQUEST_BUTTON', 'PREPASTO_LOCATION_REQUEST_BUTTON'), ('PREPASTO_CONFIRM_TIMEZONE_BUTTON', 'PREPASTO_CONFIRM_TIMEZONE_BUTTON'), ('PREPASTO_CREATING_MEAL_TEXT', 'PREPASTO_CREATING_MEAL_TEXT'), ('PREPASTO_MEAL_BUTTON', 'PREPASTO_MEAL_BUTTON'), ('PREPASTO_DIARY_TEXT', 'PREPASTO_DIARY_TEXT'), ('PREPASTO_MEAL_DELETED_TEXT', 'PREPASTO_MEAL_DELETED_TEXT'), ('PREPASTO_ERROR_TEXT', 'PREPASTO_ERROR_TEXT'), ('PREPASTO_IS_TEXT_ONLY', 'PREPASTO_IS_TEXT_ONLY'), ('PREPASTO_LOCATION_TRY_AGAIN', 'PREPASTO_LOCATION_TRY_AGAIN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='whatsapp_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_bot.whatsappuser'),
        ),
    ]
