# Generated by Django 5.1 on 2024-09-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_rename_phone_number_whatsappuser_whatsapp_wa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappuser',
            name='whatsapp_id',
        ),
    ]
