# Generated by Django 5.1 on 2024-08-31 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_meal_id'),
        ('whatsapp_bot', '0002_alter_whatsappmessage_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='meal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.meal'),
        ),
    ]
