# Generated by Django 5.1 on 2024-10-23 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_alter_whatsappmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='onboarding_step',
            field=models.CharField(choices=[('INITIAL', 'Initial WhatsApp Contact'), ('GOALS_SET', 'Nutrition Goals Set'), ('COMPLETED', 'Onboarding Completed')], default='INITIAL', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='whatsapp_profile_name',
            field=models.CharField(default='not set', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('DELETE_REQUEST', 'DELETE_REQUEST'), ('TIMEZONE_CONFIRMATION', 'TIMEZONE_CONFIRMATION'), ('TIMEZONE_CANCELLATION', 'TIMEZONE_CANCELLATION'), ('TEXT', 'TEXT'), ('LOCATION_SHARE', 'LOCATION_SHARE'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('STATUS_UPDATE_SENT', 'STATUS_UPDATE_SENT'), ('STATUS_UPDATE_READ', 'STATUS_UPDATE_READ'), ('STATUS_UPDATE_FAILED', 'STATUS_UPDATE_FAILED'), ('STATUS_UPDATE_DELIVERED', 'STATUS_UPDATE_DELIVERED'), ('NEW_USER_TEXT', 'NEW_USER_TEXT'), ('NEW_USER_LOCATION_SHARE', 'NEW_USER_LOCATION_SHARE'), ('NEW_USER_TIMEZONE_CONFIRMATION', 'NEW_USER_TIMEZONE_CONFIRMATION'), ('NEW_USER_TIMEZONE_CANCELLATION', 'NEW_USER_TIMEZONE_CANCELLATION'), ('NEW_USER_MESSAGE_GENERIC', 'NEW_USER_MESSAGE_GENERIC'), ('NEW_USER_STATUS_UPDATE_SENT', 'NEW_USER_STATUS_UPDATE_SENT'), ('NEW_USER_STATUS_UPDATE_READ', 'NEW_USER_STATUS_UPDATE_READ'), ('NEW_USER_STATUS_UPDATE_FAILED', 'NEW_USER_STATUS_UPDATE_FAILED'), ('NEW_USER_STATUS_UPDATE_DELIVERED', 'NEW_USER_STATUS_UPDATE_DELIVERED'), ('USER_DELETE_REQUEST', 'USER_DELETE_REQUEST'), ('USER_TEXT', 'USER_TEXT'), ('USER_IMAGE', 'USER_IMAGE'), ('USER_VIDEO', 'USER_VIDEO'), ('USER_MESSAGE_GENERIC', 'USER_MESSAGE_GENERIC'), ('USER_STATUS_UPDATE_SENT', 'USER_STATUS_UPDATE_SENT'), ('USER_STATUS_UPDATE_READ', 'USER_STATUS_UPDATE_READ'), ('USER_STATUS_UPDATE_FAILED', 'USER_STATUS_UPDATE_FAILED'), ('USER_STATUS_UPDATE_DELIVERED', 'USER_STATUS_UPDATE_DELIVERED'), ('PREPASTO_ONBOARDING_TEXT', 'PREPASTO_ONBOARDING_TEXT'), ('PREPASTO_CONTACT_CARD', 'PREPASTO_CONTACT_CARD'), ('PREPASTO_REQUEST_FEEDBACK', 'PREPASTO_REQUEST_FEEDBACK'), ('PREPASTO_CONFIRM_USER_TEXT', 'PREPASTO_CONFIRM_USER_TEXT'), ('PREPASTO_LOCATION_REQUEST_BUTTON', 'PREPASTO_LOCATION_REQUEST_BUTTON'), ('PREPASTO_CONFIRM_TIMEZONE_BUTTON', 'PREPASTO_CONFIRM_TIMEZONE_BUTTON'), ('PREPASTO_CREATING_MEAL_TEXT', 'PREPASTO_CREATING_MEAL_TEXT'), ('PREPASTO_MEAL_BUTTON', 'PREPASTO_MEAL_BUTTON'), ('PREPASTO_DIARY_TEXT', 'PREPASTO_DIARY_TEXT'), ('PREPASTO_MEAL_DELETED_TEXT', 'PREPASTO_MEAL_DELETED_TEXT'), ('PREPASTO_ERROR_TEXT', 'PREPASTO_ERROR_TEXT'), ('PREPASTO_IS_TEXT_ONLY', 'PREPASTO_IS_TEXT_ONLY'), ('PREPASTO_LOCATION_TRY_AGAIN', 'PREPASTO_LOCATION_TRY_AGAIN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='time_zone_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
