# Generated by Django 5.1 on 2024-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0006_alter_whatsappmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
