# Generated by Django 5.1 on 2024-10-24 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0007_whatsappuser_is_subscribed_whatsappuser_onboarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='calorie_goal',
            field=models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='carb_g_goal',
            field=models.IntegerField(default=313, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='fat_g_goal',
            field=models.IntegerField(default=56, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='whatsappuser',
            name='protein_g_goal',
            field=models.IntegerField(default=188, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('DELETE_REQUEST', 'DELETE_REQUEST'), ('EDIT_MEAL_REQUEST', 'EDIT_MEAL_REQUEST'), ('DUPLICATE_MEAL_REQUEST', 'DUPLICATE_MEAL_REQUEST'), ('MEAL_EDIT_CONFIRM', 'MEAL_EDIT_CONFIRM'), ('MEAL_EDIT_CANCEL', 'MEAL_EDIT_CANCEL'), ('NUTRITION_DATA_REQUEST', 'NUTRITION_DATA_REQUEST'), ('CONFIRM_NUTRITION_GOALS', 'CONFIRM_NUTRITION_GOALS'), ('CANCEL_NUTRITION_GOALS', 'CANCEL_NUTRITION_GOALS'), ('TIMEZONE_CONFIRMATION', 'TIMEZONE_CONFIRMATION'), ('TIMEZONE_CANCELLATION', 'TIMEZONE_CANCELLATION'), ('PREPASTO_UNDERSTANDING', 'PREPASTO_UNDERSTANDING'), ('NUTRITION_GOAL_DATA', 'NUTRITION_GOAL_DATA'), ('TEXT', 'TEXT'), ('LOCATION_SHARE', 'LOCATION_SHARE'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('STATUS_UPDATE_SENT', 'STATUS_UPDATE_SENT'), ('STATUS_UPDATE_READ', 'STATUS_UPDATE_READ'), ('STATUS_UPDATE_FAILED', 'STATUS_UPDATE_FAILED'), ('STATUS_UPDATE_DELIVERED', 'STATUS_UPDATE_DELIVERED'), ('PREPASTO_SET_GOALS_FLOW', 'PREPASTO_SET_GOALS_FLOW'), ('PREPASTO_CONFIRM_NUTRITION_BUTTON', 'PREPASTO_CONFIRM_NUTRITION_BUTTON'), ('PREPASTO_UNDERSTANDING_BUTTON', 'PREPASTO_UNDERSTANDING_BUTTON'), ('PREPASTO_ONBOARDING_TEXT', 'PREPASTO_ONBOARDING_TEXT'), ('PREPASTO_CONTACT_CARD', 'PREPASTO_CONTACT_CARD'), ('PREPASTO_REQUEST_FEEDBACK', 'PREPASTO_REQUEST_FEEDBACK'), ('PREPASTO_CONFIRM_USER_TEXT', 'PREPASTO_CONFIRM_USER_TEXT'), ('PREPASTO_LOCATION_REQUEST_BUTTON', 'PREPASTO_LOCATION_REQUEST_BUTTON'), ('PREPASTO_CONFIRM_TIMEZONE_BUTTON', 'PREPASTO_CONFIRM_TIMEZONE_BUTTON'), ('PREPASTO_CREATING_MEAL_TEXT', 'PREPASTO_CREATING_MEAL_TEXT'), ('PREPASTO_MEAL_BUTTON', 'PREPASTO_MEAL_BUTTON'), ('PREPASTO_DIARY_TEXT', 'PREPASTO_DIARY_TEXT'), ('PREPASTO_MEAL_DELETED_TEXT', 'PREPASTO_MEAL_DELETED_TEXT'), ('PREPASTO_ERROR_TEXT', 'PREPASTO_ERROR_TEXT'), ('PREPASTO_IS_TEXT_ONLY', 'PREPASTO_IS_TEXT_ONLY'), ('PREPASTO_LOCATION_TRY_AGAIN', 'PREPASTO_LOCATION_TRY_AGAIN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappuser',
            name='onboarding_step',
            field=models.CharField(choices=[('INITIAL', 'Initial WhatsApp Contact'), ('GOALS_SET', 'Nutrition Goals Set'), ('TIMEZONE_SET', 'Timezone Set'), ('COMPLETED', 'Onboarding Completed')], default='INITIAL', max_length=50),
        ),
    ]
