mock_lambda_output_dinner = {
    "meal_requester_whatsapp_wa_id": "17204768288",
    "original_message": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
    "meal_data": {
        "description": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
        "dishes": [
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
        ],
        "total_nutrition": {"calories": 988, "carbs": 138, "fat": 40, "protein": 17},
    },
    "unhandled_errors": None,
    "seconds_elapsed": 24.12915349006653,
}

mock_lambda_output_triple_dinner = {
    "meal_requester_whatsapp_wa_id": "17204768288",
    "original_message": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
    "meal_data": {
        "description": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
        "dishes": [
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
        ],
        "total_nutrition": {"calories": 2964, "carbs": 414, "fat": 120, "protein": 51},
    },
    "unhandled_errors": None,
    "seconds_elapsed": 24.12915349006653,
}

mock_lambda_output_6x_dinner = {
    "meal_requester_whatsapp_wa_id": "17204768288",
    "original_message": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
    "meal_data": {
        "description": "half a pound dry of gluten free spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
        "dishes": [
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
                        {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
            {
                "name": "gluten-free spaghetti",
                "usual_ingredients": ["rice flour", "corn flour", "quinoa flour"],
                "state": "dry",
                "qualifiers": "gluten-free",
                "confirmed_ingredients": [],
                "amount": "1/2 pound dry",
                "similar_foods": ["gluten-free pasta", "rice noodles"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004", "4002"],
                "prepasto_usda_code": "102977",
                "usda_food_data_central_id": "2343843",
                "usda_food_data_central_food_name": "Pasta, gluten free",
                "nutrition_citation_website": "USDA",
                "grams": 227,
                "nutrition": {"calories": 406, "carbs": 86, "fat": 2, "protein": 7},
            },
            {
                "name": "pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "pine nuts",
                    "garlic",
                    "olive oil",
                ],
                "state": "jarred",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/2 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": "None",
                "usda_food_data_central_id": "None",
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 93,
                "nutrition": {"calories": 372, "carbs": 6, "fat": 37, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "frozen",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "1/3 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420"],
                "prepasto_usda_code": "104303",
                "usda_food_data_central_id": "2345198",
                "usda_food_data_central_food_name": "Peas and carrots, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 151,
                "nutrition": {"calories": 88, "carbs": 17, "fat": 1, "protein": 4},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "ripe banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 126,
                "nutrition": {"calories": 122, "carbs": 29, "fat": 0, "protein": 1},
            },
        ],
        "total_nutrition": {"calories": 5928, "carbs": 828, "fat": 240, "protein": 102},
    },
    "unhandled_errors": None,
    "seconds_elapsed": 24.12915349006653,
}