mock_lambda_output_dinner = {
    "meal_requester_whatsapp_wa_id": "17204768288",
    "original_message": "half a pound of dry spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
    "meal_data": {
        "description": "half a pound of dry spaghetti, half a jar of trader joes pesto sauce, 1/3 a pound of frozen peas and one banana",
        "dishes": [
            {
                "name": "dry spaghetti",
                "usual_ingredients": ["semolina", "water"],
                "state": "cooked",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "0.5 pound",
                "similar_foods": ["pasta", "linguine", "fettuccine"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["4004"],
                "prepasto_usda_code": "102975",
                "usda_food_data_central_id": "2343841",
                "usda_food_data_central_food_name": "Pasta, cooked",
                "nutrition_citation_website": "USDA",
                "grams": 454,
                "nutrition": {"calories": 713, "carbs": 139, "fat": 4, "protein": 26},
            },
            {
                "name": "Trader Joe's pesto sauce",
                "usual_ingredients": [
                    "basil",
                    "parmesan cheese",
                    "olive oil",
                    "pine nuts",
                    "garlic",
                ],
                "state": "fresh",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "0.5 jar",
                "similar_foods": ["basil pesto", "pesto alla genovese"],
                "brand_name": "Trader Joe's",
                "chain_restaurant": None,
                "fndds_categories": [],
                "prepasto_usda_code": None,
                "usda_food_data_central_id": None,
                "usda_food_data_central_food_name": None,
                "nutrition_citation_website": "AI estimate",
                "grams": 95,
                "nutrition": {"calories": 380, "carbs": 6, "fat": 38, "protein": 5},
            },
            {
                "name": "frozen peas",
                "usual_ingredients": ["peas"],
                "state": "cooked",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "0.33 pound",
                "similar_foods": ["green peas", "sweet peas"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6420", "6418"],
                "prepasto_usda_code": "104578",
                "usda_food_data_central_id": "2345483",
                "usda_food_data_central_food_name": "Green peas, frozen, cooked, no added fat",
                "nutrition_citation_website": "USDA",
                "grams": 150,
                "nutrition": {"calories": 117, "carbs": 21, "fat": 0, "protein": 8},
            },
            {
                "name": "banana",
                "usual_ingredients": [],
                "state": "raw",
                "qualifiers": None,
                "confirmed_ingredients": [],
                "amount": "one",
                "similar_foods": ["plantain", "apple banana"],
                "brand_name": None,
                "chain_restaurant": None,
                "fndds_categories": ["6004"],
                "prepasto_usda_code": "103842",
                "usda_food_data_central_id": "2344720",
                "usda_food_data_central_food_name": "Banana, raw",
                "nutrition_citation_website": "USDA",
                "grams": 118,
                "nutrition": {"calories": 114, "carbs": 27, "fat": 0, "protein": 1},
            },
        ],
        "total_nutrition": {"calories": 1324, "carbs": 193, "fat": 42, "protein": 40},
    },
    "unhandled_errors": None,
    "seconds_elapsed": 22.78713035583496,
}
